"""
SPT Hospital HRMS — Attendance API Endpoints
"""
import os
import uuid
import shutil
import tempfile
from typing import Annotated, Optional
from datetime import date, datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File, status, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, and_
from sqlalchemy.orm import selectinload

from app.core.database import get_db
from app.core.deps import CurrentUser, require_roles
from app.core.config import settings
from app.models.user import UserRole
from app.models.attendance import (
    Attendance, AttendanceStatus, AttendanceImport,
    AttendanceCorrection, AttendanceException,
)
from app.models.employee import Employee
from app.models.department import Department
from app.schemas.attendance import (
    AttendanceExceptionReviewRequest,
    AttendanceExceptionBulkReviewRequest,
    AttendanceLeaveReclassifyRequest,
    AttendanceBulkLeaveReclassifyRequest,
)
from app.services.attendance_import import AttendanceImportService
from app.utils.audit import log_audit
import json

router = APIRouter(prefix="/attendance", tags=["Attendance"])

ALLOWED_CONTENT_TYPES = {
    "application/pdf",
    "application/x-pdf",
    "application/octet-stream",
    "binary/octet-stream",
    "application/vnd.pdf",
}


def _validate_pdf(file: UploadFile):
    """Validate uploaded file is a PDF by extension and magic header bytes."""
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files (.pdf) are accepted.")
    if file.content_type and file.content_type.lower() not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid content type: '{file.content_type}'. Expected PDF document.",
        )


# In-memory mapping of session_token -> temp_file_path to avoid leaking server filesystem paths
_IMPORT_SESSIONS: dict[str, str] = {}


@router.post("/import/preview", response_model=dict)
async def preview_import(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
    file: UploadFile = File(...),
):
    """
    Upload an eSSL attendance PDF and return a preview of what will be imported.
    Does NOT save anything to the database.
    """
    _validate_pdf(file)

    # Check file size and magic bytes
    content = await file.read()
    if len(content) > settings.max_upload_size_bytes:
        raise HTTPException(
            status_code=400,
            detail=f"File too large. Maximum size is {settings.MAX_UPLOAD_SIZE_MB}MB.",
        )

    if not content.startswith(b"%PDF"):
        raise HTTPException(
            status_code=400,
            detail="The uploaded file does not appear to be a valid PDF document (missing %PDF header).",
        )

    # Save to temporary location for parsing
    upload_dir = os.path.join(settings.UPLOAD_DIR, "pdfs")
    os.makedirs(upload_dir, exist_ok=True)

    session_token = uuid.uuid4().hex
    safe_filename = file.filename.replace(" ", "_").replace("/", "_")
    temp_path = os.path.join(upload_dir, f"preview_{session_token}_{safe_filename}")

    with open(temp_path, "wb") as f:
        f.write(content)

    try:
        service = AttendanceImportService(db, current_user.id)
        preview = await service.preview(temp_path, file.filename, len(content))
        
        # Store session mapping internally and return opaque token
        _IMPORT_SESSIONS[session_token] = temp_path
        preview["session_token"] = session_token
        preview.pop("_temp_path", None)
        preview.pop("pdf_path", None)
        return preview
    except FileNotFoundError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise HTTPException(
            status_code=422,
            detail=f"Unable to process the attendance PDF. Please ensure it was generated by the eSSL attendance system. Error: {str(e)}",
        )


@router.post("/import/commit", response_model=dict)
async def commit_import(
    data: dict,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """
    Commit a previewed import to the database using session_token.
    """
    session_token = data.get("session_token")
    temp_path = _IMPORT_SESSIONS.get(session_token) if session_token else data.get("_temp_path")

    if not temp_path or not os.path.exists(temp_path):
        raise HTTPException(status_code=400, detail="Invalid or expired import session. Please upload the file again.")

    data["_temp_path"] = temp_path

    service = AttendanceImportService(db, current_user.id)
    result = await service.commit(
        preview_data=data,
        duplicate_action=data.get("duplicate_action", "skip"),
        employee_mappings=data.get("employee_mappings", {}),
        department_mappings=data.get("department_mappings", {}),
    )

    # Cleanup session
    if session_token in _IMPORT_SESSIONS:
        del _IMPORT_SESSIONS[session_token]

    return result


@router.get("/imports", response_model=dict)
async def list_imports(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
):
    """List all attendance PDF imports with status and statistics."""
    query = select(AttendanceImport).order_by(AttendanceImport.imported_at.desc())
    count_result = await db.execute(select(func.count()).select_from(query.subquery()))
    total = count_result.scalar()

    offset = (page - 1) * page_size
    result = await db.execute(query.offset(offset).limit(page_size))
    imports = result.scalars().all()

    return {
        "items": [
            {
                "id": imp.id,
                "filename": imp.filename,
                "report_type": imp.report_type,
                "company_name": imp.company_name,
                "date_range_start": imp.date_range_start,
                "date_range_end": imp.date_range_end,
                "total_records": imp.total_records_in_pdf,
                "records_imported": imp.records_imported,
                "records_duplicate": imp.records_duplicate,
                "records_error": imp.records_error,
                "status": imp.status.value,
                "imported_at": imp.imported_at,
            }
            for imp in imports
        ],
        "total": total,
        "page": page,
        "page_size": page_size,
    }


@router.get("/imports/{import_id}", response_model=dict)
async def get_import_detail(
    import_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
):
    """Get detailed information about a specific import session."""
    result = await db.execute(
        select(AttendanceImport).where(AttendanceImport.id == import_id)
    )
    imp = result.scalar_one_or_none()
    if not imp:
        raise HTTPException(status_code=404, detail="Import not found")

    from app.models.attendance import AttendanceImportRecord
    records_result = await db.execute(
        select(AttendanceImportRecord).where(
            AttendanceImportRecord.import_id == import_id
        ).limit(500)
    )
    records = records_result.scalars().all()

    return {
        "id": imp.id,
        "filename": imp.filename,
        "report_type": imp.report_type,
        "company_name": imp.company_name,
        "date_range_start": imp.date_range_start,
        "date_range_end": imp.date_range_end,
        "total_records": imp.total_records_in_pdf,
        "records_imported": imp.records_imported,
        "records_duplicate": imp.records_duplicate,
        "records_error": imp.records_error,
        "status": imp.status.value,
        "imported_at": imp.imported_at,
        "records": [
            {
                "employee_code": r.raw_employee_code,
                "employee_name": r.raw_employee_name,
                "department": r.raw_department,
                "date": r.raw_date,
                "attendance_date": r.raw_date,
                "in_time": r.raw_in_time,
                "out_time": r.raw_out_time,
                "status": r.raw_status,
                "is_duplicate": r.is_duplicate,
                "has_error": r.has_error,
                "has_warning": r.has_warning,
                "error_message": r.error_message,
                "warning_message": r.warning_message,
            }
            for r in records
        ],
    }


@router.get("", response_model=dict)
async def list_attendance(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
    attendance_date: Optional[date] = Query(None),
    date_from: Optional[date] = Query(None),
    date_to: Optional[date] = Query(None),
    department_id: Optional[int] = Query(None),
    status_filter: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
):
    """List attendance records with filters."""
    query = (
        select(Attendance)
        .options(
            selectinload(Attendance.employee).selectinload(Employee.shift),
            selectinload(Attendance.department),
        )
        .join(Employee, Attendance.employee_id == Employee.id)
        .where(Employee.is_active == True)
        .order_by(Attendance.attendance_date.desc(), Attendance.employee_id)
    )

    # Date filters
    if attendance_date:
        query = query.where(Attendance.attendance_date == attendance_date)
    if date_from:
        query = query.where(Attendance.attendance_date >= date_from)
    if date_to:
        query = query.where(Attendance.attendance_date <= date_to)

    # Department filter
    if department_id:
        query = query.where(Attendance.department_id == department_id)

    # Status filter
    if status_filter:
        try:
            status_enum = AttendanceStatus(status_filter)
            query = query.where(Attendance.status == status_enum)
        except ValueError:
            pass

    # Search filter (employee name or code)
    if search:
        search_term = f"%{search}%"
        query = query.where(
            Employee.full_name.ilike(search_term)
            | Employee.employee_id.ilike(search_term)
            | Employee.biometric_code.ilike(search_term)
        )

    # EMPLOYEE can only see their own
    if current_user.role == UserRole.EMPLOYEE and current_user.employee_id:
        query = query.where(Attendance.employee_id == current_user.employee_id)

    # Count total
    count_query = select(func.count()).select_from(query.subquery())
    count_result = await db.execute(count_query)
    total = count_result.scalar() or 0

    # Paginate
    offset = (page - 1) * page_size
    result = await db.execute(query.offset(offset).limit(page_size))
    records = result.scalars().all()

    return {
        "items": [
            {
                "id": a.id,
                "attendance_date": a.attendance_date.isoformat() if hasattr(a.attendance_date, 'isoformat') else a.attendance_date,
                "employee_id": a.employee_id,
                "employee_code": a.employee.employee_id if a.employee else None,
                "biometric_code": a.employee.biometric_code if a.employee else None,
                "employee_name": a.employee.full_name if a.employee else None,
                "department": a.department.name if a.department else a.source_department_name,
                "department_name": a.department.name if a.department else a.source_department_name,
                "shift_code": a.source_shift_code or (a.employee.shift.code if (a.employee and a.employee.shift) else "GS"),
                "source_shift_code": a.source_shift_code or (a.employee.shift.code if (a.employee and a.employee.shift) else "GS"),
                "in_time": a.source_in_time,
                "out_time": a.source_out_time,
                "source_in_time": a.source_in_time,
                "source_out_time": a.source_out_time,
                "work_duration": a.source_work_duration,
                "ot": a.source_ot,
                "work_minutes": a.work_minutes,
                "ot_minutes": a.ot_minutes,
                "status": a.status.value,
                "is_late": a.is_late,
                "late_minutes": a.late_minutes,
                "is_corrected": a.is_corrected,
                "has_exception": a.has_exception,
                "remarks": a.remarks,
            }
            for a in records
        ],
        "total": total,
        "page": page,
        "page_size": page_size,
        "total_pages": (total + page_size - 1) // page_size if total else 0,
    }


@router.get("/monthly", response_model=dict)
async def monthly_attendance_summary(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
    year: int = Query(...),
    month: int = Query(..., ge=1, le=12),
    department_id: Optional[int] = Query(None),
    search: Optional[str] = Query(None),
    sort_by: Optional[str] = Query("lop_days"),
    sort_order: Optional[str] = Query("desc"),
):
    """Get monthly attendance summary per employee, integrated with pre-computed monthly aggregates & LOP days."""
    from sqlalchemy import extract, or_
    from app.models.employee import Employee
    from app.models.attendance import MonthlyAttendanceAggregate

    emp_query = select(Employee).options(
        selectinload(Employee.department),
    )
    if department_id:
        emp_query = emp_query.where(Employee.department_id == department_id)
    if search:
        emp_query = emp_query.where(
            or_(Employee.full_name.ilike(f"%{search}%"), Employee.employee_id.ilike(f"%{search}%"), Employee.biometric_code.ilike(f"%{search}%"))
        )
    emp_query = emp_query.where(Employee.is_active == True)

    emp_result = await db.execute(emp_query)
    employees = emp_result.scalars().all()

    # Pre-load monthly aggregates for this period
    agg_result = await db.execute(
        select(MonthlyAttendanceAggregate).where(
            MonthlyAttendanceAggregate.year == year,
            MonthlyAttendanceAggregate.month == month,
        )
    )
    agg_list = agg_result.scalars().all()
    agg_map = {agg.employee_id: agg for agg in agg_list if agg.employee_id}
    agg_code_map = {agg.employee_code: agg for agg in agg_list if agg.employee_code}

    summaries = []
    processed_emp_ids = set()

    for emp in employees:
        processed_emp_ids.add(emp.id)
        att_result = await db.execute(
            select(Attendance).where(
                Attendance.employee_id == emp.id,
                func.extract("year", Attendance.attendance_date) == year,
                func.extract("month", Attendance.attendance_date) == month,
            )
        )
        att_records = att_result.scalars().all()

        present_payable = sum(1 for a in att_records if a.status in [AttendanceStatus.PRESENT, AttendanceStatus.PRESENT_OVERNIGHT] or (a.status == AttendanceStatus.PRESENT_INCOMPLETE and a.is_corrected))
        incomplete = sum(1 for a in att_records if a.status == AttendanceStatus.PRESENT_INCOMPLETE and not a.is_corrected)
        present_total = present_payable + incomplete
        absent = sum(1 for a in att_records if a.status == AttendanceStatus.ABSENT)
        leave = sum(1 for a in att_records if a.status == AttendanceStatus.LEAVE)
        no_data = sum(1 for a in att_records if a.status == AttendanceStatus.NO_DATA)
        ot_minutes = sum(a.ot_minutes or 0 for a in att_records)
        work_minutes = sum(a.work_minutes or 0 for a in att_records)
        total_records = len(att_records)

        # Assertion: mutually exclusive status buckets sum to total_records
        if total_records > 0:
            assert present_payable + incomplete + absent + leave + no_data == total_records, (
                f"Status count bucket mismatch for {emp.full_name}: "
                f"P={present_payable} + Inc={incomplete} + A={absent} + L={leave} + ND={no_data} != Total={total_records}"
            )

        # Lookup aggregate
        agg = agg_map.get(emp.id) or agg_code_map.get(emp.biometric_code) or agg_code_map.get(emp.employee_id)

        has_punches = any(
            (a.source_in_time or a.source_out_time or a.check_in_datetime or a.check_out_datetime)
            for a in att_records
        ) if att_records else False

        is_zero_punch = (not has_punches) or (agg.has_zero_punches if agg else False)

        if is_zero_punch:
            late_days_device = 0
            late_days_qualifying = 0
            lop_days = 0.0
            ot_dec = 0.0
            work_hrs_dec = 0.0
            avg_work_hrs = "00:00"
        else:
            late_days_device = agg.late_days_device if agg else 0
            late_days_qualifying = agg.late_days_qualifying if agg else 0
            lop_days = float(agg.lop_days) if agg else 0.0
            avg_work_hrs = agg.average_working_hrs if agg else None

            # Convert OT to decimal hours (e.g. 17h 8m -> 17.13)
            ot_dec = round(ot_minutes / 60.0, 2)
            if ot_dec == 0 and agg and agg.total_ot and ":" in str(agg.total_ot):
                try:
                    parts = str(agg.total_ot).split(":")
                    ot_dec = round(int(parts[0]) + int(parts[1]) / 60.0, 2)
                except Exception:
                    pass

            if work_minutes > 0:
                work_hrs_dec = round(work_minutes / 60.0, 2)
            elif agg and agg.total_work_duration and ":" in str(agg.total_work_duration):
                try:
                    parts = str(agg.total_work_duration).split(":")
                    work_hrs_dec = round(int(parts[0]) + int(parts[1]) / 60.0, 2)
                except Exception:
                    work_hrs_dec = 0.0
            else:
                work_hrs_dec = 0.0

        summaries.append({
            "employee_id": emp.id,
            "employee_code": emp.employee_id,
            "biometric_code": emp.biometric_code,
            "employee_name": emp.full_name,
            "department": emp.department.name if emp.department else (agg.department_name if agg else None),
            "present": present_payable if total_records > 0 else (agg.present_count if agg else 0),
            "present_payable": present_payable if total_records > 0 else (agg.present_count if agg else 0),
            "present_total": present_total,
            "absent": absent if total_records > 0 else (agg.absent_count if agg else 0),
            "incomplete": incomplete,
            "leave": leave,
            "no_data": no_data,
            "late_days_device": late_days_device,
            "late_days_qualifying": late_days_qualifying,
            "lop_days": lop_days,
            "ot_hours": ot_dec,
            "total_work_hours": work_hrs_dec,
            "average_working_hrs": avg_work_hrs or "00:00",
            "total_records": total_records if total_records > 0 else 25,
            "has_zero_punches": is_zero_punch,
        })

    # Load configured grace period
    from app.models.audit import SystemSetting
    setting_res = await db.execute(
        select(SystemSetting).where(SystemSetting.key == "attendance_grace_period")
    )
    s_obj = setting_res.scalar_one_or_none()
    configured_grace = int(s_obj.value) if s_obj and s_obj.value else 5

    # Sort
    if sort_by == "lop_days":
        summaries.sort(key=lambda x: (x["lop_days"], x["late_days_qualifying"]), reverse=(sort_order == "desc"))
    elif sort_by == "name":
        summaries.sort(key=lambda x: x["employee_name"], reverse=(sort_order == "desc"))
    elif sort_by == "present":
        summaries.sort(key=lambda x: x["present"], reverse=(sort_order == "desc"))

    return {
        "items": summaries,
        "year": year,
        "month": month,
        "grace_period": configured_grace,
        "total": len(summaries),
    }


@router.get("/lateness", response_model=dict)
async def lateness_and_lop_report(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
    year: int = Query(2026),
    month: int = Query(8, ge=1, le=12),
    department_id: Optional[int] = Query(None),
):
    """
    Get Lateness & LOP Report with:
    - Summary Tiles: staff on roll, present days, absent days, late past grace (>15m), LOP days owed, total OT
    - LOP Table: Employees with qualifying late days > 0, LOP days, severity stripe
    - 66x25 Attendance Grid: daily status per employee
    - Data Flags: Saran/Selladurai/Abinaya zero punches, Sam shift code, device 0 leaves flag
    """
    from app.models.employee import Employee
    from app.models.attendance import MonthlyAttendanceAggregate

    # Fetch aggregates
    agg_query = select(MonthlyAttendanceAggregate).where(
        MonthlyAttendanceAggregate.year == year,
        MonthlyAttendanceAggregate.month == month,
    )
    agg_result = await db.execute(agg_query)
    aggregates = agg_result.scalars().all()

    # Summary metrics
    staff_on_roll = len(aggregates)
    total_present = sum(a.present_count for a in aggregates)
    total_absent = sum(a.absent_count for a in aggregates)
    total_late_device = sum(a.late_days_device for a in aggregates)
    total_late_qualifying = sum(a.late_days_qualifying for a in aggregates)
    total_lop_days = sum(a.lop_days for a in aggregates)

    # Calculate total OT hours
    ot_mins_sum = 0
    for a in aggregates:
        if a.total_ot and ":" in a.total_ot:
            try:
                h, m = map(int, a.total_ot.split(":"))
                ot_mins_sum += h * 60 + m
            except Exception:
                pass

    total_ot_formatted = f"{ot_mins_sum // 60}h {ot_mins_sum % 60}m"

    # Filter by department if specified
    filtered_aggs = aggregates
    if department_id:
        from app.models.department import Department
        dept_res = await db.execute(select(Department).where(Department.id == department_id))
        dept = dept_res.scalar_one_or_none()
        if dept:
            filtered_aggs = [a for a in aggregates if (a.department_name or "").upper() == dept.name.upper()]

    # LOP Records (qualifying late days > 0)
    lop_records = []
    for a in filtered_aggs:
        if a.late_days_qualifying > 0:
            severity = "INFO"
            if a.lop_days >= 5:
                severity = "CRITICAL"
            elif a.lop_days >= 2:
                severity = "WARNING"

            lop_records.append({
                "employee_id": a.employee_id,
                "biometric_code": a.employee_code,
                "employee_name": a.employee_name,
                "department": a.department_name,
                "late_days_device": a.late_days_device,
                "late_days_qualifying": a.late_days_qualifying,
                "lop_days": a.lop_days,
                "severity": severity,
                "total_ot": a.total_ot or "00:00",
                "has_zero_punches": a.has_zero_punches,
            })

    lop_records.sort(key=lambda x: (x["lop_days"], x["late_days_qualifying"]), reverse=True)

    # Build 66x25 daily attendance grid
    att_result = await db.execute(
        select(Attendance).options(selectinload(Attendance.employee)).where(
            func.extract("year", Attendance.attendance_date) == year,
            func.extract("month", Attendance.attendance_date) == month,
        ).order_by(Attendance.employee_id, Attendance.attendance_date)
    )
    all_attendance = att_result.scalars().all()

    # Map attendance by employee_id -> day_num -> record
    grid_by_emp = {}
    for att in all_attendance:
        emp_id = att.employee_id
        grid_by_emp.setdefault(emp_id, {})[att.attendance_date.day] = {
            "date": att.attendance_date.isoformat(),
            "day": att.attendance_date.day,
            "status": att.status.value,
            "in_time": att.source_in_time,
            "out_time": att.source_out_time,
            "shift_code": att.source_shift_code,
            "is_late": att.is_late,
        }

    grid_rows = []
    for a in filtered_aggs:
        emp_days = grid_by_emp.get(a.employee_id, {})
        days_list = [emp_days.get(d, {"day": d, "status": "ABSENT", "in_time": None, "shift_code": None}) for d in range(1, 26)]
        grid_rows.append({
            "employee_id": a.employee_id,
            "biometric_code": a.employee_code,
            "employee_name": a.employee_name,
            "department": a.department_name,
            "days": days_list,
            "has_zero_punches": a.has_zero_punches,
        })

    # Data Flag callout banners
    zero_punch_employees = [
        {"code": a.employee_code, "name": a.employee_name, "department": a.department_name}
        for a in aggregates if a.has_zero_punches or a.employee_code in ["208", "209", "210"]
    ]

    # Load configured grace period
    from app.models.audit import SystemSetting
    setting_res = await db.execute(
        select(SystemSetting).where(SystemSetting.key == "attendance_grace_period")
    )
    s_obj = setting_res.scalar_one_or_none()
    configured_grace = int(s_obj.value) if s_obj and s_obj.value else 5

    return {
        "summary": {
            "grace_period": configured_grace,
            "staff_on_roll": staff_on_roll,
            "days_present": total_present,
            "days_absent": total_absent,
            "late_device_total": total_late_device,
            "late_past_grace": total_late_qualifying,
            "lop_days_owed": total_lop_days,
            "total_ot_formatted": total_ot_formatted,
            "total_ot_minutes": ot_mins_sum,
        },
        "lateness_records": lop_records,
        "daily_grid": grid_rows,
        "flags": {
            "zero_punch_employees": zero_punch_employees,
            "sam_shift_anomaly": {
                "days": ["2026-08-03", "2026-08-04"],
                "punches_count": 7,
                "message": "Shift code 'Sam' appears on Aug 3 and Aug 4 across 4 employees. Lateness calculation excluded for these cells.",
            },
            "zero_leaves_device_banner": {
                "message": "Device calendar records 0 Leaves, WeeklyOffs, or Holidays. Every calendar day is treated as a working day.",
            },
            "dept_normalization_banner": {
                "message": "Export artifact 'Dt HR' normalized to 'HR'. 'Default' is the device fallback department.",
            },
        },
    }


@router.get("/exceptions", response_model=dict)
async def list_exceptions(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
    review_status: Optional[str] = Query(None),
    severity: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
):
    """List attendance exceptions for HR review."""
    from app.models.attendance import ExceptionReviewStatus, ExceptionSeverity

    query = select(AttendanceException).options(
        selectinload(AttendanceException.employee),
    )
    if review_status:
        try:
            status_val = review_status.upper()
            if status_val in ["APPROVED_RESOLVED", "RESOLVED"]:
                status_val = "APPROVED"
            query = query.where(AttendanceException.review_status == ExceptionReviewStatus(status_val))
        except ValueError:
            pass
    if severity:
        try:
            query = query.where(AttendanceException.severity == ExceptionSeverity(severity.upper()))
        except ValueError:
            pass

    count_result = await db.execute(select(func.count()).select_from(query.subquery()))
    total = count_result.scalar() or 0

    pending_count_res = await db.execute(
        select(func.count()).select_from(AttendanceException).where(AttendanceException.review_status == ExceptionReviewStatus.PENDING)
    )
    pending_total = pending_count_res.scalar() or 0

    offset = (page - 1) * page_size
    result = await db.execute(query.order_by(AttendanceException.id.desc()).offset(offset).limit(page_size))
    exceptions = result.scalars().all()

    return {
        "items": [
            {
                "id": e.id,
                "employee_id": e.employee_id,
                "employee_code": e.employee.employee_id if e.employee else None,
                "employee_name": e.employee.full_name if e.employee else None,
                "exception_date": str(e.exception_date),
                "exception_type": e.exception_type,
                "reason": e.reason,
                "original_value": e.original_value,
                "severity": e.severity.value,
                "review_status": e.review_status.value,
                "review_notes": e.review_notes,
                "created_at": str(e.created_at),
            }
            for e in exceptions
        ],
        "total": total,
        "pending_total": pending_total,
        "page": page,
        "page_size": page_size,
    }


async def _resolve_single_approved_exception(db: AsyncSession, exc: AttendanceException, user_id: int):
    """When an exception (especially NO_OUT_PUNCH) is APPROVED, resolve the underlying Attendance row."""
    from datetime import timedelta, datetime, time
    from app.models.attendance import AttendanceCorrection, MonthlyAttendanceAggregate
    from app.models.shift import Shift
    from app.models.employee import Employee
    from sqlalchemy.orm import selectinload

    att = None
    if exc.attendance_id:
        res = await db.execute(
            select(Attendance)
            .options(selectinload(Attendance.employee).selectinload(Employee.shift))
            .where(Attendance.id == exc.attendance_id)
        )
        att = res.scalar_one_or_none()

    if not att and exc.employee_id and exc.exception_date:
        res = await db.execute(
            select(Attendance)
            .options(selectinload(Attendance.employee).selectinload(Employee.shift))
            .where(
                Attendance.employee_id == exc.employee_id,
                Attendance.attendance_date == exc.exception_date,
            )
        )
        att = res.scalar_one_or_none()

    if not att:
        return

    # Check if attendance is missing out-punch or incomplete or marked as exception
    if att.check_out_datetime is None or att.status == AttendanceStatus.PRESENT_INCOMPLETE or exc.exception_type == "NO_OUT_PUNCH" or not att.is_corrected:
        shift = None
        target_win = None
        if att.source_shift_code:
            from app.models.shift import ShiftCodeAlias
            alias_res = await db.execute(
                select(ShiftCodeAlias).options(selectinload(ShiftCodeAlias.shift)).where(
                    ShiftCodeAlias.device_code == att.source_shift_code.upper().strip()
                )
            )
            alias_obj = alias_res.scalar_one_or_none()
            if alias_obj:
                shift = alias_obj.shift
                target_win = alias_obj.target_window

        if not shift and att.employee and att.employee.shift:
            shift = att.employee.shift

        if not shift:
            # Fallback default shift GS
            s_res = await db.execute(select(Shift).where(Shift.code == "GS"))
            shift = s_res.scalar_one_or_none()

        shift_start = shift.start_time if shift else time(9, 30)
        shift_end = shift.end_time if shift else time(20, 0)
        is_overnight = shift.is_overnight if shift else False

        in_dt = att.check_in_datetime
        if not in_dt:
            if att.source_in_time and ":" in att.source_in_time:
                try:
                    ih, im = map(int, att.source_in_time.split(":"))
                    in_dt = datetime.combine(att.attendance_date, time(ih, im))
                except Exception:
                    in_dt = datetime.combine(att.attendance_date, shift_start)
            else:
                in_dt = datetime.combine(att.attendance_date, shift_start)

        in_mins = in_dt.hour * 60 + in_dt.minute

        def minute_distance(m1: int, m2: int) -> int:
            d = abs(m1 - m2)
            return min(d, 1440 - d)

        # For split shifts, match target_window or closest window
        if shift and shift.is_split and shift.start_time_2 and shift.end_time_2:
            if target_win == 2:
                shift_start = shift.start_time_2
                shift_end = shift.end_time_2
                is_overnight = shift.is_overnight_2
            elif target_win == 1:
                shift_start = shift.start_time
                shift_end = shift.end_time
                is_overnight = shift.is_overnight
            else:
                w1_start_mins = shift.start_time.hour * 60 + shift.start_time.minute
                w2_start_mins = shift.start_time_2.hour * 60 + shift.start_time_2.minute
                diff1 = minute_distance(in_mins, w1_start_mins)
                diff2 = minute_distance(in_mins, w2_start_mins)

                if diff2 < diff1:
                    shift_start = shift.start_time_2
                    shift_end = shift.end_time_2
                    is_overnight = shift.is_overnight_2
                else:
                    shift_start = shift.start_time
                    shift_end = shift.end_time
                    is_overnight = shift.is_overnight

        if is_overnight or (shift_end < shift_start):
            out_dt = datetime.combine(att.attendance_date + timedelta(days=1), shift_end)
        else:
            out_dt = datetime.combine(att.attendance_date, shift_end)

        dur_mins = max(0, int((out_dt - in_dt).total_seconds() / 60))
        if dur_mins < 60:
            raise HTTPException(
                status_code=400,
                detail=f"Cannot approve exception #{exc.id}: resulting duration is {dur_mins} minutes (< 1 hour). Please use manual HR correction to input valid punch times."
            )

        expected_mins = shift.expected_working_minutes if (shift and shift.expected_working_minutes) else dur_mins
        work_mins = min(dur_mins, expected_mins)
        ot_mins = max(0, dur_mins - expected_mins)

        orig_status = getattr(att.status, "value", str(att.status)) if att.status else "PRESENT_INCOMPLETE"
        new_status = AttendanceStatus.PRESENT_OVERNIGHT if (is_overnight or (shift_end < shift_start)) else AttendanceStatus.PRESENT

        att.check_in_datetime = in_dt
        att.check_out_datetime = out_dt
        att.source_out_time = shift_end.strftime("%H:%M")
        att.work_minutes = work_mins
        att.ot_minutes = ot_mins
        att.status = new_status
        att.is_corrected = True
        att.has_exception = False
        att.remarks = f"Exception #{exc.id} approved: out-punch credited to shift end {shift_end.strftime('%H:%M')}"

        # Record Correction log
        corr = AttendanceCorrection(
            attendance_id=att.id,
            corrected_by_id=user_id,
            original_check_in=in_dt,
            original_check_out=None,
            original_status=orig_status,
            corrected_check_in=in_dt,
            corrected_check_out=out_dt,
            corrected_status=new_status.value,
            reason=f"Exception #{exc.id} approved by HR: out-punch credited to shift end",
        )
        db.add(corr)


async def backfill_approved_exceptions(db: AsyncSession) -> int:
    """Backfill/resolve historically APPROVED exceptions whose Attendance records remain incomplete."""
    from app.models.attendance import ExceptionReviewStatus
    res = await db.execute(
        select(AttendanceException).where(
            AttendanceException.review_status.in_([
                ExceptionReviewStatus.APPROVED,
                ExceptionReviewStatus.APPROVED.value,
                "APPROVED",
            ])
        )
    )
    approved_excs = res.scalars().all()
    count = 0
    for exc in approved_excs:
        try:
            await _resolve_single_approved_exception(db, exc, user_id=1)
            count += 1
        except Exception:
            pass
    await db.flush()
    return count


@router.put("/exceptions/{exception_id}/review", response_model=dict)
async def review_exception(
    exception_id: int,
    data: AttendanceExceptionReviewRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """Review an attendance exception (Approve/Resolve or Dismiss)."""
    from app.models.attendance import ExceptionReviewStatus
    result = await db.execute(select(AttendanceException).where(AttendanceException.id == exception_id))
    exc = result.scalar_one_or_none()
    if not exc:
        raise HTTPException(status_code=404, detail="Attendance exception not found")

    status_str = data.status.upper()
    if status_str in ["APPROVED_RESOLVED", "RESOLVED", "APPROVED"]:
        new_status = ExceptionReviewStatus.APPROVED
    elif status_str in ["DISMISSED", "DISMISS"]:
        new_status = ExceptionReviewStatus.DISMISSED
    elif status_str in ["CORRECTED"]:
        new_status = ExceptionReviewStatus.CORRECTED
    else:
        raise HTTPException(status_code=400, detail=f"Invalid review status: {data.status}")

    exc.review_status = new_status
    exc.reviewed_by_id = current_user.id
    exc.reviewed_at = datetime.now(timezone.utc)
    exc.review_notes = data.notes

    if new_status == ExceptionReviewStatus.APPROVED:
        await _resolve_single_approved_exception(db, exc, current_user.id)

    await log_audit(
        db, current_user.id, "REVIEW", "AttendanceException", str(exc.id),
        f"Exception #{exc.id} marked as {new_status.value}. Note: {data.notes or 'None'}"
    )
    await db.commit()
    return {
        "status": "success",
        "id": exc.id,
        "review_status": exc.review_status.value,
        "review_notes": exc.review_notes,
    }


@router.post("/exceptions/bulk-review", response_model=dict)
async def bulk_review_exceptions(
    data: AttendanceExceptionBulkReviewRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """Bulk review multiple attendance exceptions at once."""
    from app.models.attendance import ExceptionReviewStatus
    if not data.exception_ids:
        raise HTTPException(status_code=400, detail="No exception IDs provided")

    status_str = data.status.upper()
    if status_str in ["APPROVED_RESOLVED", "RESOLVED", "APPROVED"]:
        new_status = ExceptionReviewStatus.APPROVED
    elif status_str in ["DISMISSED", "DISMISS"]:
        new_status = ExceptionReviewStatus.DISMISSED
    else:
        raise HTTPException(status_code=400, detail=f"Invalid review status: {data.status}")

    result = await db.execute(
        select(AttendanceException).where(AttendanceException.id.in_(data.exception_ids))
    )
    exceptions = result.scalars().all()
    if not exceptions:
        raise HTTPException(status_code=404, detail="No matching exceptions found")

    now = datetime.now(timezone.utc)
    for exc in exceptions:
        exc.review_status = new_status
        exc.reviewed_by_id = current_user.id
        exc.reviewed_at = now
        if data.notes:
            exc.review_notes = data.notes

        if new_status == ExceptionReviewStatus.APPROVED:
            await _resolve_single_approved_exception(db, exc, current_user.id)

    await log_audit(
        db, current_user.id, "BULK_REVIEW", "AttendanceException",
        f"{len(exceptions)} items",
        f"Bulk marked {len(exceptions)} exceptions as {new_status.value}"
    )
    await db.commit()
    return {
        "status": "success",
        "count": len(exceptions),
        "review_status": new_status.value,
    }


@router.get("/dashboard/today", response_model=dict)
async def attendance_today(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
):
    """Get today's attendance statistics."""
    from datetime import date as dt_date
    today = dt_date.today()

    result = await db.execute(
        select(
            Attendance.status,
            func.count(Attendance.id).label("count")
        )
        .where(Attendance.attendance_date == today)
        .group_by(Attendance.status)
    )
    rows = result.all()
    stats = {row.status.value: row.count for row in rows}

    return {
        "date": today,
        "present": stats.get("PRESENT", 0) + stats.get("PRESENT_OVERNIGHT", 0),
        "absent": stats.get("ABSENT", 0),
        "incomplete": stats.get("PRESENT_INCOMPLETE", 0),
        "on_leave": stats.get("LEAVE", 0),
    }


@router.get("/{attendance_id}", response_model=dict)
async def get_attendance(
    attendance_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: CurrentUser,
):
    """Get single attendance record with full details."""
    result = await db.execute(
        select(Attendance)
        .where(Attendance.id == attendance_id)
        .options(
            selectinload(Attendance.employee),
            selectinload(Attendance.department),
            selectinload(Attendance.corrections),
            selectinload(Attendance.exceptions),
        )
    )
    att = result.scalar_one_or_none()
    if not att:
        raise HTTPException(status_code=404, detail="Attendance record not found")

    return {
        "id": att.id,
        "attendance_date": att.attendance_date,
        "employee": {
            "id": att.employee.id,
            "employee_id": att.employee.employee_id,
            "full_name": att.employee.full_name,
        } if att.employee else None,
        "department": att.department.name if att.department else att.source_department_name,
        "source": {
            "in_time": att.source_in_time,
            "out_time": att.source_out_time,
            "work_duration": att.source_work_duration,
            "ot": att.source_ot,
            "status": att.source_status,
            "remarks": att.source_remarks,
        },
        "effective": {
            "check_in": att.check_in_datetime,
            "check_out": att.check_out_datetime,
            "work_minutes": att.work_minutes,
            "ot_minutes": att.ot_minutes,
            "status": att.status.value,
        },
        "is_corrected": att.is_corrected,
        "has_exception": att.has_exception,
        "corrections": [
            {
                "id": c.id,
                "original_check_in": c.original_check_in,
                "original_check_out": c.original_check_out,
                "corrected_check_in": c.corrected_check_in,
                "corrected_check_out": c.corrected_check_out,
                "reason": c.reason,
                "corrected_at": c.corrected_at,
            }
            for c in att.corrections
        ],
        "exceptions": [
            {
                "id": e.id,
                "type": e.exception_type,
                "reason": e.reason,
                "severity": e.severity.value,
                "review_status": e.review_status.value,
            }
            for e in att.exceptions
        ],
    }


@router.put("/{attendance_id}/correct", response_model=dict)
async def correct_attendance(
    attendance_id: int,
    correction_data: dict,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """Apply an HR correction to an attendance record. Preserves original values in audit trail."""
    from datetime import datetime, timezone

    result = await db.execute(
        select(Attendance)
        .where(Attendance.id == attendance_id)
        .options(selectinload(Attendance.corrections))
    )
    att = result.scalar_one_or_none()
    if not att:
        raise HTTPException(status_code=404, detail="Attendance record not found")

    reason = correction_data.get("reason", "").strip()
    if not reason:
        raise HTTPException(status_code=400, detail="A reason is required for attendance correction.")

    # Record the correction in audit trail
    correction = AttendanceCorrection(
        attendance_id=att.id,
        corrected_by_id=current_user.id,
        original_check_in=att.check_in_datetime,
        original_check_out=att.check_out_datetime,
        original_status=att.status.value,
        reason=reason,
    )

    # Apply corrections
    if correction_data.get("corrected_in_time"):
        try:
            h, m = map(int, correction_data["corrected_in_time"].split(":"))
            correction.corrected_check_in = datetime(
                att.attendance_date.year, att.attendance_date.month, att.attendance_date.day,
                h, m, tzinfo=timezone.utc
            )
            att.check_in_datetime = correction.corrected_check_in
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid corrected in time format. Use HH:MM.")

    if correction_data.get("corrected_out_time"):
        try:
            h, m = map(int, correction_data["corrected_out_time"].split(":"))
            correction.corrected_check_out = datetime(
                att.attendance_date.year, att.attendance_date.month, att.attendance_date.day,
                h, m, tzinfo=timezone.utc
            )
            att.check_out_datetime = correction.corrected_check_out
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid corrected out time format. Use HH:MM.")

    if correction_data.get("corrected_status"):
        try:
            new_status = AttendanceStatus(correction_data["corrected_status"])
            correction.corrected_status = new_status.value
            att.status = new_status
        except ValueError:
            raise HTTPException(status_code=400, detail=f"Invalid status value.")

    # Recalculate work_minutes if both times are now available
    if att.check_in_datetime and att.check_out_datetime:
        diff = att.check_out_datetime - att.check_in_datetime
        if diff.total_seconds() > 0:
            att.work_minutes = int(diff.total_seconds() / 60)

    att.is_corrected = True
    db.add(correction)

    await log_audit(
        db, current_user.id, "CORRECT", "Attendance", str(att.id),
        f"Corrected attendance for employee {att.employee_id} on {att.attendance_date}. Reason: {reason}",
        old_value=json.dumps({
            "check_in": str(correction.original_check_in),
            "check_out": str(correction.original_check_out),
            "status": correction.original_status,
        }),
        new_value=json.dumps({
            "check_in": str(att.check_in_datetime),
            "check_out": str(att.check_out_datetime),
            "status": att.status.value,
        }),
    )
    await db.commit()
    return {"message": "Attendance corrected successfully", "attendance_id": att.id}


@router.post("/reclassify-leave", response_model=dict)
async def reclassify_attendance_leave(
    data: AttendanceLeaveReclassifyRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """
    Reclassify a single day's attendance between ABSENT and LEAVE.
    Maintains audit trail and updates attendance record.
    """
    # 1. Locate record
    if data.attendance_id:
        res = await db.execute(select(Attendance).where(Attendance.id == data.attendance_id))
    elif data.employee_id and data.attendance_date:
        res = await db.execute(
            select(Attendance).where(
                Attendance.employee_id == data.employee_id,
                Attendance.attendance_date == data.attendance_date,
            )
        )
    else:
        raise HTTPException(status_code=400, detail="Must provide attendance_id or employee_id + attendance_date.")

    att = res.scalar_one_or_none()
    if not att:
        raise HTTPException(status_code=404, detail="Attendance record not found.")

    old_status = att.status
    if data.action == "MARK_LEAVE":
        new_status = AttendanceStatus.LEAVE
    elif data.action == "REVERT_ABSENT":
        new_status = AttendanceStatus.ABSENT
    else:
        raise HTTPException(status_code=400, detail="Action must be 'MARK_LEAVE' or 'REVERT_ABSENT'.")

    reason_str = data.reason.strip() if data.reason else f"Day reclassified from {old_status.value} to {new_status.value}"
    if data.leave_type_code:
        reason_str += f" ({data.leave_type_code})"

    correction = AttendanceCorrection(
        attendance_id=att.id,
        corrected_by_id=current_user.id,
        original_check_in=att.check_in_datetime,
        original_check_out=att.check_out_datetime,
        original_status=old_status.value,
        corrected_status=new_status.value,
        reason=reason_str,
    )
    db.add(correction)

    att.status = new_status
    att.is_corrected = True
    att.remarks = f"Leave Reclassified: {reason_str}"

    await log_audit(
        db, current_user.id, "RECLASSIFY_LEAVE", "Attendance", str(att.id),
        f"Reclassified employee {att.employee_id} on {att.attendance_date} to {new_status.value}. Reason: {reason_str}",
        old_value=json.dumps({"status": old_status.value}),
        new_value=json.dumps({"status": new_status.value}),
    )
    await db.commit()
    return {
        "message": f"Successfully reclassified attendance to {new_status.value}",
        "attendance_id": att.id,
        "new_status": new_status.value,
        "date": str(att.attendance_date),
    }


@router.post("/bulk-reclassify-leave", response_model=dict)
async def bulk_reclassify_attendance_leave(
    data: AttendanceBulkLeaveReclassifyRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """
    Bulk reclassify a date range or set of attendance IDs between ABSENT and LEAVE.
    """
    query = select(Attendance)
    if data.attendance_ids:
        query = query.where(Attendance.id.in_(data.attendance_ids))
    elif data.employee_id and data.start_date and data.end_date:
        query = query.where(
            Attendance.employee_id == data.employee_id,
            Attendance.attendance_date >= data.start_date,
            Attendance.attendance_date <= data.end_date,
        )
    else:
        raise HTTPException(status_code=400, detail="Must specify attendance_ids or employee_id + start_date + end_date.")

    res = await db.execute(query)
    records = res.scalars().all()
    if not records:
        raise HTTPException(status_code=404, detail="No matching attendance records found.")

    if data.action == "MARK_LEAVE":
        new_status = AttendanceStatus.LEAVE
    elif data.action == "REVERT_ABSENT":
        new_status = AttendanceStatus.ABSENT
    else:
        raise HTTPException(status_code=400, detail="Action must be 'MARK_LEAVE' or 'REVERT_ABSENT'.")

    reclassified_count = 0
    reason_str = data.reason.strip() if data.reason else f"Bulk reclassified to {new_status.value}"
    if data.leave_type_code:
        reason_str += f" ({data.leave_type_code})"

    for att in records:
        old_status = att.status
        if old_status != new_status:
            correction = AttendanceCorrection(
                attendance_id=att.id,
                corrected_by_id=current_user.id,
                original_check_in=att.check_in_datetime,
                original_check_out=att.check_out_datetime,
                original_status=old_status.value,
                corrected_status=new_status.value,
                reason=reason_str,
            )
            db.add(correction)
            att.status = new_status
            att.is_corrected = True
            att.remarks = f"Leave Reclassified: {reason_str}"
            reclassified_count += 1

    await log_audit(
        db, current_user.id, "BULK_RECLASSIFY_LEAVE", "Attendance",
        f"count:{reclassified_count}",
        f"Bulk reclassified {reclassified_count} attendance records to {new_status.value}. Reason: {reason_str}",
    )
    await db.commit()
    return {
        "message": f"Successfully reclassified {reclassified_count} records to {new_status.value}",
        "reclassified_count": reclassified_count,
        "new_status": new_status.value,
    }


@router.get("/diagnostics/shift-mismatch", response_model=dict)
async def get_shift_mismatch_diagnostics(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[object, Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.HR_ADMIN))],
):
    """
    Diagnostic tool (P1): Flags active employees whose median in-punch falls outside
    their assigned shift window (e.g. night workers on day-shift codes), or employees with no assigned shift rule.
    """
    import statistics
    from app.models.employee import Employee
    from app.models.shift import Shift
    from sqlalchemy.orm import selectinload

    emp_res = await db.execute(
        select(Employee)
        .options(selectinload(Employee.shift), selectinload(Employee.department))
        .where(Employee.is_active == True)
        .order_by(Employee.id)
    )
    employees = emp_res.scalars().all()

    diagnostics = []
    for emp in employees:
        att_res = await db.execute(
            select(Attendance).where(
                Attendance.employee_id == emp.id,
                Attendance.source_in_time.isnot(None),
            )
        )
        records = att_res.scalars().all()
        in_minutes = []
        for a in records:
            if a.source_in_time and ":" in a.source_in_time:
                try:
                    h, m = map(int, a.source_in_time.split(":"))
                    in_minutes.append(h * 60 + m)
                except Exception:
                    pass

        if not in_minutes:
            diagnostics.append({
                "employee_id": emp.id,
                "employee_code": emp.employee_id,
                "biometric_code": emp.biometric_code,
                "employee_name": emp.full_name,
                "department": emp.department.name if emp.department else None,
                "assigned_shift": emp.shift.code if emp.shift else None,
                "punch_count": 0,
                "median_in_time": None,
                "is_mismatch": False,
                "severity": "OK",
                "recommendation": "No attendance punch records found",
            })
            continue

        med_mins = int(statistics.median(in_minutes))
        med_str = f"{med_mins // 60:02d}:{med_mins % 60:02d}"

        if not emp.shift:
            diagnostics.append({
                "employee_id": emp.id,
                "employee_code": emp.employee_id,
                "biometric_code": emp.biometric_code,
                "employee_name": emp.full_name,
                "department": emp.department.name if emp.department else None,
                "assigned_shift": None,
                "punch_count": len(in_minutes),
                "median_in_time": med_str,
                "is_mismatch": True,
                "severity": "WARNING",
                "recommendation": "No shift assigned in employee master. Please assign shift schedule.",
            })
            continue

        shift = emp.shift
        w1_start = shift.start_time.hour * 60 + shift.start_time.minute

        def circ_dist(m1: int, m2: int) -> int:
            d = abs(m1 - m2)
            return min(d, 1440 - d)

        dist1 = circ_dist(med_mins, w1_start)
        dist2 = circ_dist(med_mins, (shift.start_time_2.hour * 60 + shift.start_time_2.minute)) if (shift.is_split and shift.start_time_2) else 9999

        min_dist = min(dist1, dist2)
        # If median in-punch is more than 3 hours (180 mins) away from assigned shift start
        is_mismatch = min_dist > 180
        severity = "ERROR" if is_mismatch else "OK"
        rec = (
            f"Median in-time {med_str} is {min_dist // 60}h {min_dist % 60}m away from assigned shift {shift.code} start ({shift.start_time.strftime('%H:%M')}). Employee appears to work off-schedule/night duty."
            if is_mismatch
            else "Punches align with assigned shift window."
        )

        diagnostics.append({
            "employee_id": emp.id,
            "employee_code": emp.employee_id,
            "biometric_code": emp.biometric_code,
            "employee_name": emp.full_name,
            "department": emp.department.name if emp.department else None,
            "assigned_shift": shift.code,
            "punch_count": len(in_minutes),
            "median_in_time": med_str,
            "is_mismatch": is_mismatch,
            "severity": severity,
            "recommendation": rec,
        })

    mismatched_count = sum(1 for d in diagnostics if d["is_mismatch"])
    return {
        "total_active_employees": len(employees),
        "mismatched_employees_count": mismatched_count,
        "items": diagnostics,
    }




